# Generated by Django 4.2.13 on 2026-01-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_assigned_to_alter_asset_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technician',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
