# Generated by Django 4.2.13 on 2026-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_asset_assets_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assets_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
