# Generated by Django 4.2.13 on 2026-01-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_asset_assets_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
