# Generated by Django 4.2.13 on 2026-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asset_maintenance_reason_alter_asset_assets_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
