# Generated by Django 4.2.13 on 2026-02-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='Private', max_length=50),
        ),
    ]
