# Generated by Django 4.2.13 on 2026-02-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
