# Generated by Django 4.2.13 on 2026-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_ticketmessage_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
