# Generated by Django 4.2.13 on 2026-03-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profile_image'),
        ('core', '0017_alter_profile_image_userpasskey'),
    ]

    operations = [
    ]
