# Generated by Django 4.2.13 on 2026-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260313_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
