# Generated by Django 4.2.13 on 2026-03-22 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_profile_phone_alter_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram_gb',
            field=models.IntegerField(blank=True, help_text='RAM in GB', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Store hardware-specific specs here'),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_capacity',
            field=models.CharField(blank=True, help_text='e.g., 512GB SSD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Malware', 'Malware / Ransomware'), ('Phishing', 'Phishing / Social Engineering'), ('Unauthorized Access', 'Unauthorized Access'), ('DDoS', 'Denial of Service (DDoS)'), ('Insider Threat', 'Insider Threat'), ('Hardware Loss', 'Hardware Loss / Physical Breach'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='cve_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='detection_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact_availability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact_confidentiality',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact_integrity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='iocs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='linked_asset',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='problems_encountered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='solutions_applied',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='threat_actor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.asset'),
        ),
    ]
