# Generated by Django 4.2.13 on 2026-03-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profile_phone_alter_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram_gb',
            field=models.IntegerField(blank=True, help_text='RAM in GB', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_capacity',
            field=models.CharField(blank=True, help_text='e.g., 512GB SSD', max_length=50, null=True),
        ),
    ]
