# Generated by Django 4.2.13 on 2026-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profile_phone_alter_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='threat_actor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
