# Generated by Django 4.2.13 on 2026-03-22 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_incident_category_incident_cve_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='threat_actor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
