# Generated by Django 4.2.13 on 2026-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_asset_firmware_version_asset_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(blank=True, help_text='The date the maintenance was or will be performed', null=True),
        ),
    ]
