# Generated by Django 4.2.13 on 2026-03-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_incident_threat_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Store hardware-specific specs here'),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
