# Generated by Django 4.2.13 on 2026-04-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_asset_firmware_version_asset_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='last_technician',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
