# Generated by Django 4.2.13 on 2026-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_incident_last_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Virus', 'Virus'), ('Worm', 'Worm'), ('Ransomware', 'Ransomware'), ('Spyware / Trojan', 'Spyware / Trojan'), ('Rootkit / Bootkit', 'Rootkit / Bootkit'), ('Malware', 'Other Malware'), ('Phishing', 'Phishing / Social Engineering'), ('Man-in-the-Middle', 'Man-in-the-Middle (MitM)'), ('XSS', 'Cross-Site Scripting (XSS)'), ('SQL Injection', 'SQL Injection (SQLi)'), ('DDoS', 'Denial of Service (DDoS)'), ('Zero-Day Exploit', 'Zero-Day Exploit'), ('Unauthorized Access', 'Unauthorized Access'), ('Credential Compromise', 'Credential Compromise'), ('Insider Threat', 'Insider Threat / Data Exfiltration'), ('Misconfiguration', 'System Misconfiguration'), ('Hardware Loss', 'Hardware Loss / Physical Breach'), ('Other', 'Other / Unclassified')], default='Other', max_length=50),
        ),
    ]
