# Generated by Django 4.2.13 on 2026-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_maintenance_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='battery_health',
            field=models.IntegerField(blank=True, help_text='Laptop/UPS battery % health', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, help_text='e.g. Dell, HP, Cisco, Juniper', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='faulty_hardware_part',
            field=models.CharField(blank=True, choices=[('Display', 'Screen/Display'), ('Battery', 'Battery'), ('Keyboard', 'Keyboard/Trackpad'), ('Storage', 'HDD/SSD/RAID Array'), ('RAM', 'Memory (RAM)'), ('Motherboard', 'Motherboard/Logic Board'), ('Power', 'PSU/Redundant Power Supply'), ('Network', 'NIC/SFP/Fiber Ports'), ('Cooling', 'Fan/Heatsink/Cooling Node'), ('Chassis', 'Physical Chassis/Rack Mount'), ('Other', 'Other Hardware Component')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_redundant_power',
            field=models.BooleanField(default=False, help_text='Does it have Dual PSUs?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, help_text='e.g. Windows Server 2022, RHEL 9', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rack_unit',
            field=models.IntegerField(blank=True, help_text='Height in U (e.g. 1, 2, 4)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='software_issue_type',
            field=models.CharField(blank=True, choices=[('OS', 'Operating System Crash/Error'), ('Firmware', 'Firmware/BIOS Corruption'), ('Driver', 'Driver Conflict/Missing'), ('Security', 'Malware/Virus Infection'), ('Update', 'Update/Patch Failure'), ('Config', 'Configuration/Registry Issue'), ('License', 'Software Licensing/Subscription'), ('ServicePack', 'Service Pack/Kernel Update'), ('Performance', 'Slow Performance/Bottleneck'), ('App', 'Third-Party Application Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_ports',
            field=models.IntegerField(blank=True, help_text='Copper/Fiber Port Count', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assets_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assets_type',
            field=models.CharField(choices=[('PC', 'Workstation/PC'), ('Laptop', 'Laptop'), ('Server', 'Server'), ('Router', 'Router'), ('Switch', 'Network Switch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='firmware_version',
            field=models.CharField(blank=True, help_text='IOS/RouterOS Version', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(help_text='Data Center/Rack/Slot', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, help_text='e.g. Dual Xeon Silver, i9-13900', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ram_gb',
            field=models.IntegerField(blank=True, help_text='Total RAM in GB', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Niche specs like Port Mapping or License Keys'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Under Maintenance'), ('Decommissioned', 'Decommissioned')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='storage_capacity',
            field=models.CharField(blank=True, help_text='e.g. 4x2TB RAID 10 SSD', max_length=100, null=True),
        ),
    ]
