# Generated by Django 4.2.13 on 2026-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_asset_battery_health_asset_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='faulty_hardware_part',
            field=models.CharField(blank=True, choices=[('Display', 'Screen/Display'), ('Battery', 'Battery'), ('Keyboard', 'Keyboard/Trackpad'), ('Storage', 'HDD/SSD/RAID Array'), ('RAM', 'Memory (RAM)'), ('Motherboard', 'Motherboard/Logic Board'), ('Power', 'PSU/Redundant Power Supply'), ('Network', 'NIC/SFP/Fiber Ports'), ('Cooling', 'Fan/Heatsink/Cooling Node'), ('Chassis', 'Physical Chassis/Rack Mount'), ('Other', 'Other Hardware Component')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='software_issue_type',
            field=models.CharField(blank=True, choices=[('OS', 'Operating System Crash/Error'), ('Firmware', 'Firmware/BIOS Corruption'), ('Driver', 'Driver Conflict/Missing'), ('Security', 'Malware/Virus Infection'), ('Update', 'Update/Patch Failure'), ('Config', 'Configuration/Registry Issue'), ('License', 'Software Licensing/Subscription'), ('ServicePack', 'Service Pack/Kernel Update'), ('Performance', 'Slow Performance/Bottleneck'), ('App', 'Third-Party Application Error')], max_length=50, null=True),
        ),
    ]
