# Generated by Django 4.2.13 on 2026-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_incident_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Virus / Worm', 'Virus / Worm'), ('Ransomware', 'Ransomware'), ('Spyware / Trojan', 'Spyware / Trojan'), ('Rootkit / Bootkit', 'Rootkit / Bootkit'), ('Malware', 'Other Malware'), ('Phishing / Social Engineering', 'Phishing / Social Engineering'), ('Man-in-the-Middle (MitM)', 'Man-in-the-Middle (MitM)'), ('Cross-Site Scripting (XSS)', 'Cross-Site Scripting (XSS)'), ('SQL Injection (SQLi)', 'SQL Injection (SQLi)'), ('Denial of Service (DDoS)', 'Denial of Service (DDoS)'), ('Zero-Day Exploit', 'Zero-Day Exploit'), ('Unauthorized Access', 'Unauthorized Access'), ('Credential Compromise', 'Credential Compromise'), ('Insider Threat / Data Exfiltration', 'Insider Threat / Data Exfiltration'), ('System Misconfiguration', 'System Misconfiguration'), ('Hardware Loss / Physical Breach', 'Hardware Loss / Physical Breach'), ('Other / Unclassified', 'Other / Unclassified')], default='Other', max_length=50),
        ),
    ]
