# Generated by Django 4.2.13 on 2026-04-16 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_alter_incident_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='attachment',
            field=models.FileField(blank=True, help_text='Manuals, Invoices, Photos', null=True, upload_to='asset_attachments/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='battery_health',
            field=models.IntegerField(blank=True, help_text='Laptop/UPS battery % health', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, help_text='e.g. Dell, HP, Cisco, Juniper', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='faulty_hardware_part',
            field=models.CharField(blank=True, choices=[('Display', 'Screen/Display'), ('Battery', 'Battery'), ('Keyboard', 'Keyboard/Trackpad'), ('Storage', 'HDD/SSD/RAID Array'), ('RAM', 'Memory (RAM)'), ('Motherboard', 'Motherboard/Logic Board'), ('Power', 'PSU/Redundant Power Supply'), ('Network', 'NIC/SFP/Fiber Ports'), ('Cooling', 'Fan/Heatsink/Cooling Node'), ('Chassis', 'Physical Chassis/Rack Mount'), ('Other', 'Other Hardware Component')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_redundant_power',
            field=models.BooleanField(default=False, help_text='Does it have Dual PSUs?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_attachment',
            field=models.FileField(blank=True, help_text='Maintenance Logs, Repair Photos', null=True, upload_to='maintenance_attachments/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, help_text='e.g. Windows Server 2022, RHEL 9', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rack_unit',
            field=models.IntegerField(blank=True, help_text='Height in U (e.g. 1, 2, 4)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='software_issue_type',
            field=models.CharField(blank=True, choices=[('OS', 'Operating System Crash/Error'), ('Firmware', 'Firmware/BIOS Corruption'), ('Driver', 'Driver Conflict/Missing'), ('Security', 'Malware/Virus Infection'), ('Update', 'Update/Patch Failure'), ('Config', 'Configuration/Registry Issue'), ('License', 'Software Licensing/Subscription'), ('ServicePack', 'Service Pack/Kernel Update'), ('Performance', 'Slow Performance/Bottleneck'), ('App', 'Third-Party Application Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_ports',
            field=models.IntegerField(blank=True, help_text='Copper/Fiber Port Count', null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='attachment',
            field=models.FileField(blank=True, help_text='Photos, Logs, Reports', null=True, upload_to='maintenance_attachments/'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='faulty_hardware_part',
            field=models.CharField(blank=True, choices=[('Display', 'Screen/Display'), ('Battery', 'Battery'), ('Keyboard', 'Keyboard/Trackpad'), ('Storage', 'HDD/SSD/RAID Array'), ('RAM', 'Memory (RAM)'), ('Motherboard', 'Motherboard/Logic Board'), ('Power', 'PSU/Redundant Power Supply'), ('Network', 'NIC/SFP/Fiber Ports'), ('Cooling', 'Fan/Heatsink/Cooling Node'), ('Chassis', 'Physical Chassis/Rack Mount'), ('Other', 'Other Hardware Component')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_attachment',
            field=models.FileField(blank=True, help_text='Additional files related to maintenance', null=True, upload_to='maintenance_attachments/'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(blank=True, help_text='The date the maintenance was or will be performed', null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='software_issue_type',
            field=models.CharField(blank=True, choices=[('OS', 'Operating System Crash/Error'), ('Firmware', 'Firmware/BIOS Corruption'), ('Driver', 'Driver Conflict/Missing'), ('Security', 'Malware/Virus Infection'), ('Update', 'Update/Patch Failure'), ('Config', 'Configuration/Registry Issue'), ('License', 'Software Licensing/Subscription'), ('ServicePack', 'Service Pack/Kernel Update'), ('Performance', 'Slow Performance/Bottleneck'), ('App', 'Third-Party Application Error')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assets_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assets_type',
            field=models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Server', 'Server'), ('Router', 'Router'), ('Switch', 'Network Switch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Under Maintenance'), ('Decommissioned', 'Decommissioned')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='storage_capacity',
            field=models.CharField(blank=True, help_text='e.g., 512GB SSD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Virus / Worm', 'Virus / Worm'), ('Ransomware', 'Ransomware'), ('Spyware / Trojan', 'Spyware / Trojan'), ('Rootkit / Bootkit', 'Rootkit / Bootkit'), ('Malware', 'Other Malware'), ('Phishing / Social Engineering', 'Phishing / Social Engineering'), ('Man-in-the-Middle (MitM)', 'Man-in-the-Middle (MitM)'), ('Cross-Site Scripting (XSS)', 'Cross-Site Scripting (XSS)'), ('SQL Injection (SQLi)', 'SQL Injection (SQLi)'), ('Denial of Service (DDoS)', 'Denial of Service (DDoS)'), ('Zero-Day Exploit', 'Zero-Day Exploit'), ('Unauthorized Access', 'Unauthorized Access'), ('Credential Compromise', 'Credential Compromise'), ('Insider Threat / Data Exfiltration', 'Insider Threat / Data Exfiltration'), ('System Misconfiguration', 'System Misconfiguration'), ('Hardware Loss / Physical Breach', 'Hardware Loss / Physical Breach'), ('Other / Unclassified', 'Other / Unclassified')], default='Other / Unclassified', max_length=50),
        ),
        migrations.CreateModel(
            name='UserTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
