# Generated by Django 4.2.13 on 2026-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_maintenance_faulty_hardware_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='attachment',
            field=models.FileField(blank=True, help_text='Manuals, Invoices, Photos', null=True, upload_to='asset_attachments/'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='attachment',
            field=models.FileField(blank=True, help_text='Photos, Logs, Reports', null=True, upload_to='maintenance_attachments/'),
        ),
    ]
