# Generated by Django 4.2.13 on 2026-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_asset_attachment_maintenance_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='maintenance_attachment',
            field=models.FileField(blank=True, help_text='Maintenance Logs, Repair Photos', null=True, upload_to='maintenance_attachments/'),
        ),
    ]
