# Generated by Django 4.2.13 on 2026-04-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_asset_maintenance_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_attachment',
            field=models.FileField(blank=True, help_text='Additional files related to maintenance', null=True, upload_to='maintenance_attachments/'),
        ),
    ]
