# Generated by Django 4.2.13 on 2026-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_usertotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='solution_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='solved_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
