# Generated by Django 4.2.13 on 2026-01-30 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='assets_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='asset',
            name='assets_id',
            field=models.CharField(default='000', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='assets_type',
            field=models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Server', 'Server')], default='PC', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default='Not Assigned', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Under Maintenance')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='actions_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.asset'),
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.asset'),
        ),
    ]
