# Generated by Django 4.2.13 on 2026-02-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketmessage'),
        ),
    ]
