# Generated by Django 4.2.13 on 2026-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketattachment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
